Added batch file for evolving Ethan
However, I'm having trouble making it run. I get the error
```
Exception in thread "main" java.lang.NoClassDefFoundError: sun/reflect/ReflectionFactory$GetReflectionFactoryAction
        at wox.serial.Util.<clinit>(Util.java:20)
        at wox.serial.SimpleWriter.write(SimpleWriter.java:52)
        at wox.serial.Easy.save(Easy.java:23)
        at edu.southwestern.evolution.EvolutionaryHistory.saveArchetype(EvolutionaryHistory.java:285)
        at edu.southwestern.evolution.EvolutionaryHistory.initArchetype(EvolutionaryHistory.java:226)
        at edu.southwestern.evolution.EvolutionaryHistory.initArchetype(EvolutionaryHistory.java:195)
        at edu.southwestern.evolution.EvolutionaryHistory.initArchetype(EvolutionaryHistory.java:177)
        at edu.southwestern.MMNEAT.MMNEAT.setupTWEANNGenotypeDataTracking(MMNEAT.java:261)
        at edu.southwestern.MMNEAT.MMNEAT.loadClasses(MMNEAT.java:778)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:867)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1073)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1033)
Caused by: java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory$GetReflectionFactoryAction
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```
This is that reoccurring issue with sun jar files. I've fixed it before in other contexts. I'm sure the code still works ... just need to find the right library. Will test more later